### ISSUE TITLE
Data required for worked examples no longer listed on Edmond

### ISSUE THREAD

**Issue by highlyavailable** [benkoger/overhead-video-worked-examples#5]
The link to the "Gelada Monkeys" and the 'Kenyan Ungulates" worked example videos is no longer stored on Edmond; can these links be updated so that this data is openly accessible?

**Comment by benkoger** [comment]
Thanks for letting us know. The data was moved from a temporary to a permanent address on edmond but the github links weren't updated. The links should work now. (Also, here is the link: https://doi.org/10.17617/3.EMRZGH)

**Comment by highlyavailable** [comment]
Thank you! @benkoger
